### ISSUE TITLE
支持gbk编码

### ISSUE THREAD

**Issue by asoqa** [alibaba/jarslink#10]
现在模块(xxx)加载失败:Line 1 in XML document from URL [jar:file:/home/admin/xxxSNAPSHOT-jar-with-dependencies.jar!/META-INF/spring/xxxx.xml] is invalid; nested exception is org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 37; Invalid encoding name "GBK".

**Comment by kiral** [comment]
使用UTF-8编码
-----------------------------
方腾飞/kiral
Email：tengfei@ifeve.com
weibo：@方腾飞-清英
Web：http://ifeve.com
