### ISSUE TITLE
请问这个和阿里内部的pandora包隔离容器的使用场景有区分吗

### ISSUE THREAD

**Issue by Viyond** [alibaba/jarslink#11]
如题。

**Comment by kiral** [comment]
test代码里是可运行的案例。

-----------------------------
方腾飞/kiral
Email：tengfei@ifeve.com
weibo：@方腾飞-清英
Web：http://ifeve.com

**Comment by luairan** [comment]
有本质区别  pandora针对中间件管理，  jarslink 个人觉得是针对模块化应用集成部署的方式

**Comment by kiral** [comment]
请加钉钉群
![http://ifeve.com/wp-content/uploads/2018/03/IMG_0244.jpg](http://ifeve.com/wp-content/uploads/2018/03/IMG_0244.jpg)
