### ISSUE TITLE
动态修改模块不会有问题吗？

### ISSUE THREAD

**Issue by kevin-wang001** [alibaba/jarslink#12]
动态修改模块的version，新旧模块切换时，会不会有负作用，不会影响正在执行的代码吗？

比如，旧容器里面的方法还没有执行完，此时去卸载旧模块会怎么样？

**Comment by kiral** [comment]
我们是先加载新的模块，加载成功后，再切流，最后再卸载旧的模块。
-----------------------------
方腾飞/kiral
Email：tengfei@ifeve.com
weibo：@方腾飞-清英
Web：http://ifeve.com

**Comment by kevin-wang001** [comment]
新的请求直接执行新模块的代码，旧模块正在执行的代码运行结束后才执行卸载动作，是这样吗？

**Comment by kiral** [comment]
是的
-----------------------------
方腾飞/kiral
Email：tengfei@ifeve.com
weibo：@方腾飞-清英
Web：http://ifeve.com
