### ISSUE TITLE
可不可以翻译成英文版

### ISSUE THREAD

**Issue by simonxl** [alibaba/jarslink#18]
我们公司在用Spring Boot，没有英文版的doc很难convince大家用这个

**Comment by kiral** [comment]
预计本月会出英文版
-----------------------------
方腾飞/kiral
Email：tengfei@ifeve.com
weibo：@方腾飞-清英
Web：http://ifeve.com

**Comment by peierlong** [comment]
支持英文版 +1

**Comment by kiral** [comment]
已经有英文版

**Comment by simonxl** [comment]
@kiral 谢谢！
