### ISSUE TITLE
有没有交流群?

### ISSUE THREAD

**Issue by 1132102260** [alibaba/jarslink#19]
本人小白一个,demo下载下来根本不会用,想请教一些大神

**Comment by pxzxj** [comment]
就按照Wiki里面的使用说明用就ok了

**Comment by tom-zhb** [comment]
但是现在不成熟啊。而且遇到一些问题，或者想扩展。能不能建立一个交流群，或者社区？

**Comment by pxzxj** [comment]
等等作者现身吧 看怎么说

**Comment by 1132102260** [comment]
@pxzxj 

就按照Wiki里面的使用说明用就ok了? 

大神,moduleManager 与module.getName() 报红,这个moduleManager与module是怎么定义的?
代码中怎么用的?

**Comment by kiral** [comment]
可以看下test代码

-----------------------------
方腾飞/kiral
Email：tengfei@ifeve.com
weibo：@方腾飞-清英
Web：http://ifeve.com

**Comment by pxzxj** [comment]
兄dei 加下我Q吧 924735714，截图啥的方便点



张雄江
浙江鹏信信息科技股份有限公司/技术开发部
18767120203
杭州市余杭区向往街1008号乐富海邦园14号楼9-10楼
 
发件人： 1132102260
发送时间： 2018-03-23 17:13
收件人： alibaba/jarslink
抄送： pxzxj; Mention
主题： Re: [alibaba/jarslink] 有没有交流群? (#19)
@pxzxj
就按照Wiki里面的使用说明用就ok了?
大神,moduleManager 与module.getName() 报红,这个moduleManager与module是怎么定义的?
代码中怎么用的?

**Comment by Dean111** [comment]
**有没有具体的与springboot,springmvc的整合过程，看着有点抽象，不知道怎么落地使用**

**Comment by pxzxj** [comment]
@1132102260，刚建了个群，群号是565276932，不清楚的群里面交流下吧

**Comment by maskleo** [comment]
建议使用[gitter](https://gitter.im/)

**Comment by YoungHu** [comment]
谢了一个很简单的demo，可以看下https://github.com/YoungHu/jarslink-demo

**Comment by kiral** [comment]
建了一个钉钉群 ，见FAQ  https://github.com/alibaba/jarslink/wiki/FAQ
