### ISSUE TITLE
模块远程调用和微服务的区别

### ISSUE THREAD

**Issue by haroldjiang** [alibaba/jarslink#20]
如果有很多模块，模块之间是在不同的jvm上，都用远程过程调用；这种场景下和微服务场景是否可以认为是一样的

**Comment by yfliuas** [comment]
jarslink中的module采用的自定义的classLoader，其实还是在一个jvm中的。jarslink解决的问题是扩展了子模块的独立性（相比于maven中module），可以独立控制和热部署。@haroldjiang

**Comment by zsjnb** [comment]
@yfliuas 原理中调用方式支持RPC跨jvm的模块间调用，又是用来做什么用的呢？实现微服务架构？

**Comment by kiral** [comment]
跨进程调用都走RPC，和微服务类似。但是微服务不解决运行时动态增加能力。
