### ISSUE TITLE
数据库操作怎么处理

### ISSUE THREAD

**Issue by yfliuas** [alibaba/jarslink#23]
按照jarslink的module处理方式，每一个module处理对应的模块，将不同的module放在不同的jar包内，这样隔离性做到位了，我的疑问是对于数据库操作这种公共操作是怎么做的？是每一个module配置一个数据源，还是有其他手段使得module共享主项目的数据源？还有一个问题，对于公共的model类就需要在主项目、module上都配置一遍或者单独抽出一个jar维护这些公共model，这样设计是否会使项目结构反而变得混乱？

**Comment by yfliuas** [comment]
面对这两个问题，阿里是如何解决或者规避这些问题？

**Comment by kiral** [comment]
1：数据源我们一般不暴露在模块中，而是做在系统里对外提供接口查询和操作。
2：公共的类放在单独的二方包里。

-----------------------------
方腾飞/kiral
Email：tengfei@ifeve.com
weibo：@方腾飞-清英
Web：http://ifeve.com

**Comment by yfliuas** [comment]
谢谢
