### ISSUE TITLE
在SpringMVC中无法进行热替换更新？？？

### ISSUE THREAD

**Issue by fannaoshaoxiang** [alibaba/jarslink#24]
本人试了一下，可以在SpringMVC中动态新增更新可以实现，但是实现类替换更新就不能实现？

具体步骤：

1.我创建了两个JAR包，相同的包名和类名称，就是里面的实现方法中返回的名称getActionName名称不一样
2.在SpringMVC中创建两个Controller方法和两个ModuleManager、ModuleLoader
3.可以实现动态的增加更新，却无法实现替换更新

**Comment by 935237604** [comment]
你是不是没有更改版本号啊，不更改版本号的话是不会重新加载的，至于新增更新可以实现是因为当前系统没有加载到该类所以会尝试从class文件加载，但是已经加载的由于版本号没有更新是不会重新去加载的。

**Comment by 935237604** [comment]
@fannaoshaoxiang

**Comment by 935237604** [comment]
@fannaoshaoxiang 已经确定这是一个BUG，正在修复中

**Comment by 935237604** [comment]
@fannaoshaoxiang 模块更新后可以使用ModuleManager.find(String name, String version)方法获取到或者先使用ModuleManager.activeVersion方法将更新后的模块设置为默认模块然后使用ModuleManager.find(String name)查找模块

**Comment by fannaoshaoxiang** [comment]
@935237604  已经更新了是吧？
