### ISSUE TITLE
支持注解方式

### ISSUE THREAD

**Issue by icc99** [alibaba/jarslink#25]
目前的bean都是只能通过xml注册,  有没有计划支持注解方式

**Comment by 935237604** [comment]
支持注解的吧，只不过系统的几个核心bean默认用xml的形式注册的，想用注解的话可以将那几个对象new出来然后用@Configuration注解加上@Bean注解注册到系统中去，不知道你说的是不是这个意思？@icc99

**Comment by 935237604** [comment]
额，刚看了下源码，你说的是模块内的Action注册啊，是只支持xml.....

**Comment by 935237604** [comment]
添加了注解支持，但是需要等管理员审核。@icc99

**Comment by kiral** [comment]
已经支持 #23
