### ISSUE TITLE
能不能发个dubbo应用场景集成的demo

### ISSUE THREAD

**Issue by zsjnb** [alibaba/jarslink#26]
如题，看使用指南多少有些混乱，代码与test里也不一样，或者有些过时？

能否提供dubbo微服务应用场景集成的案例，目前的资料都太抽象了，我一个微服务里有N多接口，然后是实现，怎么接入呢？微服务发布、远程调用怎么办？

![image](https://user-images.githubusercontent.com/33953490/38007395-cf63468a-327b-11e8-9a48-488ada06b953.png)

求大神指导！

**Comment by zsjnb** [comment]
@YoungHu 你的意思是微服务再拆分子模块，由jarslink来管理？

**Comment by YoungHu** [comment]
JarsLink说白了就是请求转发。你接口的具体业务逻辑通过Action写在模块A中，这样你就当做在JarsLink框架中开了一个口子，然后你要在主程序中发布dubbo接口，和不使用JarsLink的写法一样，唯一的区别是这个接口的实现要调用模块A的Action而不用写具体的业务逻辑代码。在JarsLink引入的模块中不能发布HTTP和dubbo这样的协议服务，只能是bean。

**Comment by kiral** [comment]
jarslink2.0会集成dubbo，预计7月左右推出，敬请期待！
