### ISSUE TITLE
子模块有spring mvc内容，如何正确mapping ?

### ISSUE THREAD

**Issue by luairan** [alibaba/jarslink#30]
父模块为标准的spring mvc 工程   子模块有mvc 的mapping 同时需要被使用。 如何操作呢？

**Comment by 935237604** [comment]
在子模块中将spring的xml配置文件放入META-INF/spring文件夹中即可

**Comment by icc99** [comment]
@JoeKerouac  这样子要另外占用一个端口吗？？ 就是父applicationContext已经占用一个端口， 模块内的applicationContext作为子 会占用另外一个端口？？？
