### ISSUE TITLE
请问下怎么实现一次加载多模块,多action啊?配置多个ModuleConfig吗?

### ISSUE THREAD

**Issue by mglj** [alibaba/jarslink#36]
如题, 求回复

**Comment by 935237604** [comment]
ModuleConfig中的moduleURL是使用的集合列表，也就是你可以通过传入多个URL来达到加载多个模块的目的，同时也可以动态的创建ModuleConfig然后使用load方法给加载到系统来。

**Comment by mglj** [comment]
感谢回复.想加载多个jar,但是不知道是应该new多个ModuleConfig还是要在一个ModuleConfig中set多个setModuleUrl,如果多个setModuleUrl那么其他参数怎么设置呢

**Comment by 935237604** [comment]
如果多个jar对应的是同一个功能模块的话建议用同一个ModuleConfig，如果是一个jar对应的一个模块的话建议使用多个ModuleConfig，这样方便区分管理不同模块。

**Comment by mglj** [comment]
您好,我第一个ModuleConfig,是在ModuleRefreshSchedulerImpl中创建的没有问题,但是第二个我创建ModuleConfig的时候就会报错 :resources length is 0.这是什么原因呢

**Comment by 935237604** [comment]
你是采用xml配置的吧，你看下你classpath下面的META-INF/spring/文件夹里是否有spring的xml配置文件。

**Comment by 935237604** [comment]
看你要加载的模块下的META-INF/spring/文件夹里是否有spring的xml配置文件。

**Comment by mglj** [comment]
是的有的

**Comment by 935237604** [comment]
额   你给你代码提交一下我看看
