### ISSUE TITLE
模块的生命周期管理

### ISSUE THREAD

**Issue by kiral** [alibaba/jarslink#38]
模块新增生命周期管理分别是初始化状态，类加载状态，对象实例化状态和注册状态。

- 初始化状态：基本检查。
- 类加载状态：模块的类已经加载完成。
- 实例化状态：模块里的对象都已经被实例化完成。
- 注册状态：把模块加载到模块池中，处于注册状态的模块才能被调用。

**Comment by icc99** [comment]
以后可以注册事件监听到这些事件？
