### ISSUE TITLE
可以给一份打包部署的方案吗？

### ISSUE THREAD

**Issue by kevin-wang001** [alibaba/jarslink#49]
可以给一份打包部署的方案吗？
比如，子模块怎么打包动态发布会比较便捷？

**Comment by kiral** [comment]
有两个方案：

方案1 拉模式

1：在本地编译代码打包成JAR包。
2：把JAR上传到一个远程文件服务器，比如阿里云的OSS。
3：应用从远程服务器下载JAR，可以把配置信息存放在JAR里，比如版本号，JAR名。

方案2 推模式

1：在本地编译代码打包成JAR包。
2：把JAR直接SCP到服务器上的某个目录。
3：应用检查服务指定目录的JAR是否有更新，如果有更新就进行加载。

-----------------------------
方腾飞/kiral  并发编程网创始人

Email：tengfei@ifeve.com
微信公众号：ifeves
weibo：@方腾飞-清英
Web：http://ifeve.com

**Comment by kevin-wang001** [comment]
那么本地测试的话，都只能用拷贝jar的形式来运行吗？
有没有更加简单的方式呢？

例如：
mod-main是主模块，mod1、mod2是jarslink子模块
我现在做测试，都是将mod1.jar和mod2.jar拷贝到mod-main的resources目录下来进行的。
有没有更简单的方式呢？不需要人为的拷贝？

├─mod-main
│  └─src
│      └─main
│         ├─java
│         │  └─com
│         │      ├─alipay
│         │      │  └─jarslink
│         │      │      └─api
│         │      │          └─impl
│         │      └─kvn
│         │          └─main
│         │              └─controller
│         ├─resources
│             ├─mod1-1.0-SNAPSHOT.jar    // 将mod1拷贝到mod-main的resources目录下
│             └─mod2-1.0-SNAPSHOT.jar    // 将mod2拷贝到mod-main的resources目录下
├─mod1
│  └─src
│      ├─main
│      │  ├─java
│      │  │  └─com
│      │  │      └─kvn
│      │  │          └─mod1
│      │  └─resources
│      │      └─META-INF
│      │          └─spring
│      └─test
│          └─java
├─mod2
   └─src
       ├─main
       │  ├─java
       │  │  └─com
       │  │      └─kvn
       │  │          └─mod2
       │  └─resources
       │      └─META-INF
       │          └─spring
       └─test
           └─java

**Comment by kevin-wang001** [comment]
我用maven-antrun-plugin解决了
