### ISSUE TITLE
controller 放到模块里，requestMapping 没有生效，有解决方案么？

### ISSUE THREAD

**Issue by fordCheng** [alibaba/jarslink#57]
controller 放到模块里，requestMapping 没有生效，有解决方案么？

**Comment by liangruisen** [comment]
controller 放到模块里，requestMapping 没有生效是因为模块扫描类之后没有将requestMapping注册到RequestMappingHandlerMapping类里面导致的。解决思路是利用反射的方式调用RequestMappingHandlerMapping对象的保护级 detectHandlerMethods 方法来注册 controller 对象，只是这样做了之后模块运行时卸载就会出现问题，尚未想到运行时卸载干净模块的方法。**注：这个思路尚未进行验证。**
