### ISSUE TITLE
在开发模式下，如何实现断点调试？

### ISSUE THREAD

**Issue by shaofq** [alibaba/jarslink#71]
正常流程是需要发布jar包，然后通过主模块调用发布的jar包，但这样在开发中调试非常复杂，有没有比较简便的方案，支持断点调试

**Comment by kiral** [comment]
在运行时可以直接断点测试的

**Comment by shaofq** [comment]
@kiral 你的意思是在class里面设置断点吗？如果不是我怎么在开发阶段不通过加载jar包的方式直接修改调试

**Comment by kiral** [comment]
是在class里设置断点

-----------------------------
方腾飞/kiral  并发编程网创始人

Email：tengfei@ifeve.com
微信公众号：ifeves
weibo：@方腾飞-清英
Web：http://ifeve.com
