### ISSUE TITLE
可以把入门文档写的详细一下吗？

### ISSUE THREAD

**Issue by ikuboo** [alibaba/jarslink#73]
比如
1.新的jar包怎么替换老的jar？
2.怎么设置版本号?

**Comment by kiral** [comment]
可以的，目前可以参考下测试用例。

**Comment by kiral** [comment]
已更新 https://github.com/alibaba/jarslink/wiki/%E5%A6%82%E4%BD%95%E4%BD%BF%E7%94%A8
