### ISSUE TITLE
多个不同的模块并存时，下一个模块加载会覆盖上一个

### ISSUE THREAD

**Issue by Evan43789596** [alibaba/jarslink#76]
我有两个模块实现相同的方法，但是两个方法处理的逻辑不一样，用于处理不同的业务特性，例如我有一个模块是提供给车贷用的，另一个模块提供给现金贷用的，想通过模块化管理，多个模块并存，通过请求的产品类型不同，自动路由到对应的模块，当时我发现jarslink只能同时存在一个模块，当存在了车贷模块时，再加载一个现金贷模块就会移除其他模块，这就做不到多个不同模块共存时根据不同的产品路由到不同的模块去处理，想问下有对应的处理方法吗

**Comment by jackcailj** [comment]
嗨，这个功能可以实现吗？
