### ISSUE TITLE
关于JarsLink的使用教程和解析

### ISSUE THREAD

**Issue by Evan43789596** [alibaba/jarslink#77]
感谢jarslink的作者，让我之前一直想搞的模块化处理实现了，感觉对做审批那一块特别有用，我在我公众号简单整理了一些关于JarsLink的解析和教程，后续会放一些实战的demo和公司实战场景，有兴趣的朋友可以关注下Eshare分享

**Comment by kiral** [comment]
感谢！可以加下我们钉钉群 JarsLink开源框架对外讨论群
