### ISSUE TITLE
更新jar包 moduleConfig修改version字段提示这个错误

### ISSUE THREAD

**Issue by nosixtools** [alibaba/jarslink#80]
提示 LogFactory.release(classLoader);  没有release这个方法
java.lang.NoSuchMethodError: org.apache.commons.logging.LogFactory.release(Ljava/lang/ClassLoader;)V
	at com.alipay.jarslink.api.impl.SpringModule.clear(SpringModule.java:203) ~[jarslink-api-1.6.1.20180301.jar:na]

**Comment by kiral** [comment]
参考使用文档，需要依赖相关POM

https://github.com/alibaba/jarslink/wiki/%E5%A6%82%E4%BD%95%E4%BD%BF%E7%94%A8 <https://github.com/alibaba/jarslink/wiki/%E5%A6%82%E4%BD%95%E4%BD%BF%E7%94%A8>
-----------------------------
方腾飞/kiral  并发编程网创始人

Email：tengfei@ifeve.com
微信公众号：ifeves
weibo：@方腾飞-清英
Web：http://ifeve.com

**Comment by nosixtools** [comment]
spring-jcl的Jar包冲突引起的 已解决
